#!/usr/bin/env bash

## Description: Initialize stack and testing environment in DDEV.
## Usage: pantheon-testenv [environment_name] [optional profile_or_recipe]
## Example: ddev pantheon-testenv my-env minimal
## Aliases: pantheon:testenv,testenv

#ddev-generated

# Abort if anything fails
set -e

#-------------------------- Helper functions ------------------------------

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'
divider='===================================================\n'

#-------------------------- Execution -------------------------------------

# Check if at least one argument is provided.
if [ -z "$1" ]; then
    echo -e "\n ❌  Usage: ddev pantheon-testenv <environment_name> [optional profile_or_recipe]"
    exit 1
fi

# Set the variables from the inputs.
# Default to "minimal" profile if not provided.
ENVNAME=$1
PROFILERECIPE=${2:-minimal}

echo -e "🚧 ${yellow} Initializing test environment: ${ENVNAME} ${NC} 🚧"
echo -e "${green}${divider}${NC}"

# Ensure we are in the project root.
cd ${DDEV_APPROOT}

echo -e "🚧 ${yellow} Initializing Cypress.${NC} 🚧"
echo -e "${green}${divider}${NC}"
ddev cypress-install

# Site initialization.
echo -e "🚧 ${yellow} Composer install.${NC} 🚧"
echo -e "${green}${divider}${NC}"
ddev composer install

# Run site installation with the given profile/recipe
ddev drush si -y $PROFILERECIPE

# Log in
echo -e "🔑 ${yellow} Logging you in. ${NC} 🔑"
ddev drush uli

# Complete
echo -e "🎉 ${yellow} Build complete!!! ${NC} 🎉"
echo -e "${green}${divider}${NC}"
