#!/usr/bin/env bash

## Description: Authorizes you into DDEV.
## Usage: project-auth
## Example: "ddev project-auth"
## Aliases: project:auth

#ddev-generated

#-------------------------- Helper functions ------------------------------

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'
divider='===================================================\n'

#-------------------------- Execution -------------------------------------

# Auth.
echo -e "🔑 ${yellow} Adding keys.${NC} 🔑"
echo -e "${green}${divider}${NC}"
ddev auth ssh
