#!/usr/bin/env bash

## Description: Initialize local development.
## Usage: project-init
## Example: "ddev project-init"
## Aliases: project:init,init

#ddev-generated

#-------------------------- Helper functions ------------------------------

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'
divider='===================================================\n'
theme_tools_command='ddev theme-build'
critical_tools_command='ddev critical-install'

#-------------------------- Execution -------------------------------------

echo -e "🚀 ${yellow} Initializing the Project.${NC} 🚀"
echo -e "${green}${divider}${NC}"
ddev start -y

# Set up Lefthook.
ddev project-lefthook

# Add SSH keys for remote access.
ddev project-auth

# Install Composer dependencies.
if [ -f "composer.json" ]; then
  echo -e "🚧 ${yellow} Installing Composer dependencies.${NC} 🚧"
  echo -e "${green}${divider}${NC}"
  ddev composer install
fi

# Get the DB
ddev db-refresh

# Set up NVM.
ddev project-nvm

# Install Cypress.
ddev cypress-install

# Install theme tools.
ddev theme-install

# Prime Acqui CLI.
HOSTING_PROVIDER=$(ddev exec printenv HOSTING_PROVIDER)
if [ "$HOSTING_PROVIDER" = "acquia" ]; then
  # Ensure telemetry is disabled.
  ddev exec 'echo "no" | acli hello-world'
fi

# Log in.
ddev drupal-uli

# Complete.
echo -e "🎉 ${yellow} Build complete!!!${NC} 🎉"
echo -e "Visit ${yellow}${DDEV_PRIMARY_URL}${NC} in a web browser."
echo -e "Run ${yellow}${theme_tools_command}${NC} to work on the theme."
echo -e "Run ${yellow}${critical_tools_command}${NC} to install tools for Critical CSS."
echo -e "${green}${divider}${NC}"
