site_name: DDEV Kanopi Drupal Add-on
site_description: Comprehensive DDEV add-on for Drupal development with multi-provider hosting support
site_url: https://kanopi.github.io/ddev-kanopi-drupal/
repo_url: https://github.com/kanopi/ddev-kanopi-drupal
repo_name: kanopi/ddev-kanopi-drupal

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy

nav:
  - Home: index.md
  - Commands: commands.md
  - Custom Configuration: custom-configuration.md
  - Advanced:
    - Troubleshooting: troubleshooting.md
    - Contributing: contributing.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kanopi/ddev-kanopi-drupal
  generator: false

copyright: Copyright &copy; 2025 Kanopi Studios
