#!/usr/bin/env bash

## Description: Install and set up theme development tools in DDEV
## Usage: theme-install
## Example: ddev theme-install
## Aliases: theme:install,install-theme-tools,thi

#ddev-generated

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'
divider='===================================================\n'

#-------------------------- Settings --------------------------------

# Define paths.
FULL_THEME_PATH="/var/www/html/${DDEV_DOCROOT}/${THEME}"

#-------------------------- Execution -------------------------------------

# Theme initialization message
echo -e "🚧 ${yellow} Installing theme development tools. ${NC} 🚧"
echo -e "${green}${divider}${NC}"

# Move to the theme directory
echo -e "🚀 ${yellow} Navigating to theme directory: ${FULL_THEME_PATH} ${NC} 🚀"
echo -e "${green}${divider}${NC}"
cd "${FULL_THEME_PATH}"

# Install NPM dependencies
echo -e "🚧 ${yellow} Installing NPM dependencies. ${NC} 🚧"
echo -e "${green}${divider}${NC}"

export NVM_DIR="$HOME/.nvm" || echo "export NVM_DIR=$HOME/.nvm"
source "$NVM_DIR/nvm.sh" || echo "source $NVM_DIR/nvm.sh"
echo "NVM version: $(nvm --version)"

# Use Node version specified in .nvmrc
NODE_VERSION=$(cat "${FULL_THEME_PATH}/.nvmrc")
echo "Using Node.js version: ${NODE_VERSION}"
nvm install "${NODE_VERSION}" || echo "nvm install"
nvm alias default "${NODE_VERSION}" || echo "nvm alias"
nvm use || echo "nvm use"
npm install --save patch-package || echo "npm install"

# Compile theme assets
echo -e "🚧 ${yellow} Compiling theme assets. ${NC} 🚧"
echo -e "${green}${divider}${NC}"
npm run build || echo "npm run build"

# Completion message
echo -e "🎉 ${yellow} Theme setup complete! ${NC} 🎉"
echo -e "To start watching for file changes, run: ${yellow}ddev theme-watch${NC}"
echo -e "${green}${divider}${NC}"
